spring:
  shardingsphere:
    #shardingsphere 数据源环境配置
    data-source:
      names: master0,master0slave,master1,master1slave
      master0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: qvYx8OaG
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localdb.mysql.com:3307/ds_3?characterEncoding=utf-8
        username: w_account
      master0slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 63ucwRVV
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localdb.mysql.com:3308/ds_3?characterEncoding=utf-8
        username: r_account
      master1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: qvYx8OaG
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localdb.mysql.com:3309/ds_3?characterEncoding=utf-8
        username: w_account
      master1slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 63ucwRVV
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localdb.mysql.com:3310/ds_3?characterEncoding=utf-8
        username: r_account