spring:
  # shardingsphere公共配置
  shardingsphere:
    props:
      sql:
        show: true
    sharding:
      master-slave-rules:
        master0:
          master-data-source-name: master0
          slave-data-source-names:
            - master0slave
          load-balance-algorithm-type: ROUND_ROBIN
        master1:
          master-data-source-name: master1
          slave-data-source-names:
            - master1slave
          load-balance-algorithm-type: ROUND_ROBIN
      broadcast-tables:
        - t_region_config
        - t_sys_config
      binding-tables:
        - t_order_base,t_order_item
      default-data-source-name: master0
      default-database-strategy:
        inline:
          algorithm-expression: master$->{order_id % 2}
          sharding-column: order_id
      tables:
        t_order_base:
          actual-data-nodes: master$->{0..1}.t_order_base
          database-strategy:
            inline:
              algorithm-expression: master$->{order_id % 2}
              sharding-column: order_id
        t_order_item:
          actual-data-nodes: master$->{0..1}.t_order_item
          database-strategy:
            inline:
              algorithm-expression: master$->{order_id % 2}
              sharding-column: order_id 
        t_user_order_mapping:
          actual-data-nodes: master$->{0..1}.t_user_order_mapping
          database-strategy:
            inline:
              algorithm-expression: master$->{user_id % 2}
              sharding-column: user_id