mybatis:
  config-location: classpath:META-INF/mybatis-config.xml
  mapper-locations: classpath:META-INF/mappers/*Mapper.xml
server:
  port: 8084
spring:
  devtools:
    restart:
      enabled: true
  profiles:
    active: ds,shardingsphere
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
 