mybatis:
  config-location: classpath:META-INF/mybatis-config.xml
  mapper-locations: classpath:META-INF/mappers/*Mapper.xml
server:
  port: 8084
spring:
  devtools:
    restart:
      enabled: true
  shardingsphere:
    dataSources:
      master0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: qvYx8OaG
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3307/ds_3?characterEncoding=utf-8
        username: w_account
      master0slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 63ucwRVV
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3308/ds_3?characterEncoding=utf-8
        username: r_account
      master1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: qvYx8OaG
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3309/ds_3?characterEncoding=utf-8
        username: w_account
      master1slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 63ucwRVV
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3310/ds_3?characterEncoding=utf-8
        username: r_account
      names: master0,master0slave,master1,master1slave
    props:
      #check-table-metadata-enabled: true
      sql:
        show: true
    sharding:
      binding-tables:
      - t_order_base,t_order_item
      broadcast-tables:
      - t_region_config,t_sys_config
      default-data-source-name: master0
      default-database-strategy:
        inline:
          algorithm-expression: master$->{order_id % 2}
          sharding-column: order_id
      master-slave-rules:
        master0:
          master-data-source-name: master0
          slave-data-source-names: master0slave
        master1:
          master-data-source-name: master1
          slave-data-source-names: master1slave
      tables:
        t_order_base:
          actual-data-nodes: master$->{0..1}.t_order_base
        t_order_item:
          actual-data-nodes: master$->{0..1}.t_order_item
        t_user_order_mapping:
          actual-data-nodes: master$->{0..1}.t_user_order_mapping
          database-strategy:
            inline:
              algorithm-expression: master$->{user_id % 2}.t_user_order_mapping
              sharding-column: user_id
